i.pereverzev2 task 2 completed
dmitry-irtegov/NSU-OS-2024 pull request #127
Opened 2024-09-22 13:27 UTC by Takymu

2024-09-26 14:20 UTC, leadpogrommer requested changes

2024-09-26 14:20 UTC, leadpogrommer commented on 23215/i.pereverzev2/lab2/main.c
> +    if (setenv("TZ", "PST+8:00:00PDT+7:00:00,M3.2.0,M11.1.0", 1) == -1)
Зачем такое использовать? Где Вы это находите?

2024-09-26 14:20 UTC, leadpogrommer commented on 23215/i.pereverzev2/lab2/main.c
> +    if (setenv("TZ", "PST+8:00:00PDT+7:00:00,M3.2.0,M11.1.0", 1) == -1)
[А, понятно](https://www.google.com/search?q=%22PST%2B8%3A00%3A00PDT%2B7%3A00%3A00%2CM3.2.0%2CM11.1.0%22&newwindow=1&sca_esv=7746fac465ae621b&sca_upv=1&ei=42z1ZrztNODS1sQPsLDF-QM&ved=0ahUKEwj86p-m5uCIAxVgqZUCHTBYMT8Q4dUDCA8&uact=5&oq=%22PST%2B8%3A00%3A00PDT%2B7%3A00%3A00%2CM3.2.0%2CM11.1.0%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiJyJQU1QrODowMDowMFBEVCs3OjAwOjAwLE0zLjIuMCxNMTEuMS4wIkj6JFCzC1jDInACeACQAQCYAVegAf4BqgEBM7gBA8gBAPgBAZgCAKACAJgDAOIDBRIBMSBAiAYBkgcAoAeHAQ&sclient=gws-wiz-serp)

2024-09-29 05:58 UTC, Takymu commented on 23215/i.pereverzev2/lab2/main.c
> +    if (setenv("TZ", "PST+8:00:00PDT+7:00:00,M3.2.0,M11.1.0", 1) == -1)
исправил

2024-09-30 14:13 UTC, merged